require:
  - rubocop-rspec

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

RSpec/FilePath:
  CustomTransform:
    QuickRB: quickrb

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
